### ISSUE TITLE
Feature request: use Playback Rate Shift while keeping original Pitch

### ISSUE THREAD

**Issue by ozzyogkush** [mudlord/foobar2000-plugins#1]
This is for the `foo_dsp_effect` plugin.

An example of this being useful would be learning to play a song - you want to slow it down but not change the pitch so you can play along in the correct tuning.

Would be cool to just have a checkbox that applies the correct inverse pitch change. Cockos Reaper software has this functionality for example.

**Comment by mudlord** [comment]
That would be using the "Tempo" effect?

**Comment by ozzyogkush** [comment]
Ah, that works. Should document the difference. Thanks.
